language: generic
dist: xenial
os: 
  - linux
  - osx
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck #&& luarocks install --local busted
script:
- $HOME/.luarocks/bin/luacheck .
# - $HOME/.luarocks/bin/busted .
notifications:
  email: false