@startuml Domain Model
hide circle
hide empty
skinparam IconPrivateColor Black
skinparam IconPublicColor Black
skinparam IconProtectedColor Black
skinparam IconPrivateBackgroundColor Black
skinparam IconPublicBackgroundColor #7ACFF5
skinparam ClassStereotypeFontStyle normal
skinparam Shadowing false
skinparam ClassFontStyle bold
skinparam class {
    BackgroundColor #7ACFF5
    ArrowColor Black
    BorderColor Black
}

class "Ingredient" as ING {
    - String name
    - color
}

class "Drink" as DRINK {
    - int yeast_concentration
    - int alcohol_percentage
    - int alcohol_quantity
    - Timestamp time_spent_on_barrel
    - Timestamp time_spent_on_fermenter
    - String label
    - drink()
}

class "Distilery" as DISTILERY {
    - int MAX_TEMPERATURE
    - int MIN_TEMPERATURE
    - int curr_temperature
}

class "Barrel" as BARREL {
    - Timestamp sealed_start_date
    - Timestamp sealed_end_date
    - ItemStack trace_amounts_of
    - seal()
    - unseal()
}

class "Fermenter" as FERMENTER {
    - Timestamp time_start
    - Timestamp time_end
    + calculateYeastConcentration()
    + calculateAlcoholPercentage()
    + calculateAlcoholQuantity()
}

class "Yeast" as YEAST {
    - double growth_rate
    - double lag_phase_duration
    - double death_rate
    - double stationary_phase
    + generateYeast(humidity, temperature, position)
}

class "Crusher" as CRUSHER {

}

class "Bottler" as BOTTLER {
    - craftBottles()
    - label()
}

class "Brew Kettle" as KETTLE {
    - int temperature
    - Timestamp started_boiling
    - Timestamp stopped_boiling
    - boil()
}

ING "1" -- "1..*" CRUSHER : is crushed by >
ING "1..*" -- "1" KETTLE : is brewed by >

DRINK "1" -- "1..*" KETTLE : is made in a >
DRINK "1" -- "1..*" DISTILERY : is distiled by >
DRINK "1" -- "1..*" BARREL : is aged by >
DRINK "1" -- "1..*" FERMENTER : is fermented by >
DRINK "1" -- "1" BOTTLER : is bottled \nand labeled by >

FERMENTER "*" -- "1" YEAST : uses >

@enduml